name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
      LLM_MODEL_NAME: ${{ secrets.LLM_MODEL_NAME }}
      LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone PRism repo
        run: git clone https://github.com/arghya-bandyopadhyay-30/PRism.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies for PRism
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r PRism/requirements.txt

      - name: Run PRism review
        run: |
          source .venv/bin/activate
          cp prism_rules/custom_rules.yaml PRism/config/custom_rules.yaml
          cd PRism
          python main.py --pr_url ${{ github.event.pull_request.html_url }} --config_path config/custom_rules.yaml
